management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

spring:
  flyway:
    placeholders:
      default_tenant_id: 20c6abe6-01f3-4056-8d1c-a4b3130facd6
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
bill:
  schedule:
    delete-on-startup: false
  statement:
    remote-match-lookback-months: 6
    mail-enabled: false
