apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: vault
          image: {{ .Values.image }}
          command: ["/bin/sh", "/vault/entrypoint.sh"]
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /vault/config/vault-config.hcl
              subPath: vault-config.hcl
            - name: config
              mountPath: /vault/entrypoint.sh
              subPath: entrypoint.sh
            - name: data
              mountPath: /vault/file
          readinessProbe:
            tcpSocket:
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8200
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ .Values.service.name }}
            defaultMode: 0755
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.service.name }}