apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: spring-bill
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.springProfile | quote }}
            - name: VAULT_ADDR
              value: "http://{{ .Release.Name }}-vault:8200"
            - name: VAULT_TOKEN
              value: {{ .Values.vault.token | quote }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.app.containerPort }}
            periodSeconds: 10
            failureThreshold: 24
          readinessProbe:
            tcpSocket:
              port: {{ .Values.app.containerPort }}
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.app.containerPort }}
            periodSeconds: 20
            failureThreshold: 3