apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}