apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      securityContext:
        runAsUser: {{ .Values.app.uid }}
        runAsGroup: {{ .Values.app.uid }}
        fsGroup: {{ .Values.app.uid }}
      containers:
        - name: spring-bill
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.springProfile | quote }}
            - name: VAULT_ADDR
              value: "http://{{ .Values.vault.serviceName }}:8200"
            - name: VAULT_TOKEN
              value: {{ .Values.vault.token | quote }}
          volumeMounts:
            - name: pos-storage
              mountPath: {{ .Values.bill.pos.path }}
            - name: accounts-statement-storage
              mountPath: {{ .Values.bill.accountsStatement.path }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.app.containerPort }}
            periodSeconds: 10
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.containerPort }}
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.containerPort }}
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: pos-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pos
        - name: accounts-statement-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-accounts-statement